In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [6]:
df = pd.read_csv(r"C:\Users\ARPIT\Downloads\homeprices.csv")
df


area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [8]:
#we have a missing data to solve this we will take median data

In [14]:
ndf=df.bedrooms.median()

In [18]:
df.bedrooms.fillna(ndf)
#filling nan value with the median

0    3.0
1    4.0
2    4.0
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [25]:
df.bedrooms=df.bedrooms.fillna(ndf)
df
#updatind the dataset

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [31]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)
#fit is used to train model using the provided dataset
#syntax of train= reg.fit(df[['independent variabl 1','independent variabl 2']],df.target_variable)

LinearRegression()

In [33]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [35]:
reg.intercept_

221323.0018654043

In [39]:
reg.predict([[3000,3,40]])
#price for 3000 area, 3 bedroom and 40 year old

C:\Users\ARPIT\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [49]:
m=int(input("enter the area"))
n=int(input("enter bedrooms"))
o=int(input("enter age"))
reg.predict([[m, n, o]])
#price from user input

enter the area 4325
enter bedrooms 2
enter age 2


C:\Users\ARPIT\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([746307.38760375])

In [51]:
import os
print(os.getcwd())

C:\Users\ARPIT\ML projects
